// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2557.d2015d;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// Defining variables
    public static SpeedController drivetrainSpeedController1;
    public static SpeedController drivetrainSpeedController2;  
    public static SpeedController drivetrainSpeedController3; 
    public static SpeedController drivetrainSpeedController4;
    public static SpeedController elevatorElevatorController;
    public static SpeedController liftBinsController;
    public static SpeedController intakeController;
    public static RobotDrive drivetrainRobotDrive41;
    public static Compressor pneumaticsCompressor;
    public static Gyro locationGyro;
    public static BuiltInAccelerometer locationAccelerometer;
    public static Timer time;
    public static Ultrasonic ultra;
    public static Ultrasonic ultra2;
    public static Ultrasonic ultra3;
    public static Ultrasonic ultra4;
    public static Encoder liftEncoder;
    public static Encoder leftFront;
    public static Encoder leftBack;
    public static Encoder rightBack;
    public static Encoder rightFront;
    public static Encoder binEncoder;
    public static Servo leftServo;
    public static Servo rightServo;
    public static DoubleSolenoid feeler;
    public static DoubleSolenoid grasper;
    public static DoubleSolenoid ejecter;
    public static DigitalOutput limitswitch;
   

    
   
    
    
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Details about specific systems of the robot

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainSpeedController1 = new Talon(0);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 1", (Talon) drivetrainSpeedController1);
        
        drivetrainSpeedController2 = new Talon(1);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 2", (Talon) drivetrainSpeedController2);
        
        drivetrainSpeedController3 = new Talon(2);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 3", (Talon) drivetrainSpeedController3);
        
        drivetrainSpeedController4 = new Talon(3);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 4", (Talon) drivetrainSpeedController4);
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainSpeedController1, drivetrainSpeedController2,
              drivetrainSpeedController3, drivetrainSpeedController4);
        
        drivetrainRobotDrive41.setSafetyEnabled(true);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(1.0);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        drivetrainRobotDrive41.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);     
        
        
  //      pneumaticsGrabberSolenoid = new DoubleSolenoid(0, 0, 1);      
    //    LiveWindow.addActuator("Pneumatics", "GrabberSolenoid", pneumaticsGrabberSolenoid);
        limitswitch = new DigitalOutput(3);
        
        locationGyro = new Gyro(0);
        LiveWindow.addSensor("Location", "Gyro", locationGyro);
        locationGyro.setSensitivity(0.007);
        locationAccelerometer = new BuiltInAccelerometer();
        LiveWindow.addSensor("Location", "Accelerometer", locationAccelerometer);
        //locationAccelerometer.setSensitivity(0.0);
        //locationAccelerometer.setZero(2.5);
        elevatorElevatorController = new Talon(4);
        LiveWindow.addActuator("Elevator", "Elevator Controller", (Talon) elevatorElevatorController);
        ultra = new Ultrasonic(9, 10);
        ultra.setAutomaticMode(true);
        
        
        
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
